name: Build SD Webui Forge Container

on:
  workflow_dispatch:
    inputs:
      build:
        type: choice
        description: "Release build"
        default: "latest"
        required: true
        options:
          - latest
          - dev
      version:
        description: "Version"
        default: "ub22.04-py3.10-pt2.3.1-cu12.1"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:          
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        docker-images: false

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
  
    - name: Build and Publish to Docker Hub
      uses: docker/build-push-action@v4
      with:
        file: sd-webui-forge/Dockerfile
        tags: |
          ${{secrets.DOCKER_USER}}/sd-webui-containers:forge-${{github.event.inputs.version}}
          ${{secrets.DOCKER_USER}}/sd-webui-containers:forge-${{github.event.inputs.build}}
        push: true