name: Build SD Webui Forge

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Start action ?"
        default: "Yes"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:          
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        docker-images: false

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
  
    - name: Build and Publish to Docker Hub
      uses: docker/build-push-action@v4
      with:
        file: sd-webui-forge/Dockerfile
        tags: ffxvs/sd-webui-forge:ub22.04-py3.10-tor2.1.2-cu12.1
        push: true
