name: Build SD Webui Forge

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Start action ?"
        default: "Yes"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Remove unnecessary files
      run: |
          rm -rf /usr/share/dotnet
          rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
  
    - name: Build and Publish to Docker Hub
      uses: docker/build-push-action@v4
      with:
        file: sd-webui-forge/Dockerfile
        tags: ffxvs/sd-webui-forge:py3.10-torch2.1.2-cu12.1
        push: true
